# @Inclusive.HeatSensor.Web_HostAddress = http://localhost:5141
# @Inclusive.HeatSensor.Web_HostAddress = https://icr-heat-sensor.eus2.sample-dev.azgrafana-test.io
@Inclusive.HeatSensor.Web_HostAddress = https://icr-heat-sensor.wus3.sample-dev.azgrafana-test.io

### GET Request
GET {{Inclusive.HeatSensor.Web_HostAddress}}/api/HeatSensor/
Accept: application/json

### POST Request
POST {{Inclusive.HeatSensor.Web_HostAddress}}/api/HeatSensor/
Content-Type: application/json
Accept: application/json

{
  "comment": "this is a code review comment",
  "url": "https://github.com/jonathanpeppers/inclusive-heat-sensor/issues/27#issuecomment-2465032570"
}

### POST Request
POST {{Inclusive.HeatSensor.Web_HostAddress}}/api/HeatSensor/
Content-Type: application/json
Accept: application/json

{
  "comment": "this code is very very ugly. We should stop doing it ASAP.",
  "url": "https://github.com/jonathanpeppers/inclusive-heat-sensor/issues/27#issuecomment-2465032570"
}