name: comments

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, reopened]

jobs:
  comments:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: comment if offensive or angry
        shell: pwsh
        run: |
          $body = @{
            comment = "${{ github.event.comment.body }}"
          }
          $bodyJson = $body | ConvertTo-Json -Compress
          Invoke-WebRequest -Method POST -Uri http://localhost:7241/api/heatsensor -Body $bodyJson
          & gh issue comment "${{ github.event.issue.number }}" --repo "${{ github.repository }}" --body "$BODY"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
