name: comments

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  comments:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: comment if offensive or angry
        shell: pwsh
        run: |
          Invoke-WebRequest -Method POST -Uri http://localhost:7241/api/heatsensor -Body "{ 'comment': '${{ github.event.comment.body }}'}"
          & gh issue comment "${{ github.event.issue.number }}" --repo "${{ github.repository }}" --body "$BODY"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
