name: comments

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, reopened]
  pull_request_review_comment:
    types: [created, edited]

jobs:
  comments:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Add a comment if the message was offensive or angry
        uses: jonathanpeppers/inclusive-heat-sensor@action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
