name: comments

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  comments:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Call API
        run: TODO
      - name: Add comment
        run: gh issue comment "$NUMBER" --repo "$REPO" --body "$BODY"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.repository }}
          BODY: ${{ needs.getSimilarIssues.outputs.message }}
